Перед сном
```rust
error: attempted to take value of method `iter_mut` on type `std::vec::Vec<Player>`
   --> src\main.rs:142:47
    |
142 |                                 for i in list.iter_mut {
    |                                               ^^^^^^^^
    |
    = help: maybe a `()` to call it is missing? If not, try an anonymous function
```
Не хочет сволочь!!